name: Run nanDECK and Upload Export

on:
  push

jobs:
  build-nandeck:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install fonts
      run: |
        $fontsPath = "$PWD/fonts"
        if (Test-Path $fontsPath) {
          Get-ChildItem $fontsPath -Filter *.ttf -Recurse | ForEach-Object {
            $fontFile = $_.FullName
            Copy-Item -Path $fontFile -Destination "$env:WINDIR\Fonts" -Force
            $fontName = (New-Object -ComObject Shell.Application).Namespace(0).ParseName($fontFile).GetDetailsOf($_, 21)
            Write-Host "Installing font: $fontName"
            reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts" /v "$fontName (TrueType)" /t REG_SZ /d $fontFile /f
          }
        } else {
          Write-Host "No fonts directory found, skipping font installation."
        }
      shell: pwsh

    - name: Export deck
      run: |
        .\nandeck\nanDECK.exe .\nandeck\decks\deck.txt /exec
      shell: cmd
      
    - name: Upload Export Folder
      uses: actions/upload-artifact@v4
      with:
        name: nandeck-export
        path: nandeck/export
        retention-days: 1
